# Generated by Django 5.2.4 on 2025-07-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='city_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='donor',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
