# Generated by Django 5.2.4 on 2025-07-30 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='youths/')),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city_of_origin', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('displacement_date', models.DateField(blank=True, null=True)),
                ('reason_for_displacement', models.TextField(blank=True)),
                ('current_location', models.CharField(blank=True, max_length=150)),
                ('immediate_needs', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('aspirations', models.TextField(blank=True)),
                ('family_members_count', models.IntegerField(blank=True, null=True)),
                ('seeking_help', models.BooleanField(default=False)),
                ('my_story', models.TextField(blank=True)),
                ('specific_needs_goals', models.JSONField(blank=True, default=list)),
                ('achievements_strengths', models.JSONField(blank=True, default=list)),
                ('sponsorship_impact', models.TextField(blank=True)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('alternative_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
