# Generated by Django 5.2.4 on 2025-07-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='youths/'),
        ),
    ]
