# Generated by Django 5.2.4 on 2025-07-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_alter_mentor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='role',
        ),
        migrations.AddField(
            model_name='mentor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='city_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mentor',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentor',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
