# Generated by Django 5.2.4 on 2025-07-15 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrograntApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('grant_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('budget_breakdown', models.TextField()),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_info', 'Needs More Info')], default='under_review', max_length=20)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('additional_info_required', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microgrant_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
