# Generated by Django 5.2.4 on 2025-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microgrants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrograntapplication',
            name='additional_info_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='micrograntapplication',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='micrograntapplication',
            name='additional_info_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='micrograntapplication',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_info', 'Needs More Info'), ('funded', 'Funded')], default='under_review', max_length=20),
        ),
    ]
